version: 2

before:
  hooks:
    - |
      mkdir -p ~/.gnupg
      chmod 700 ~/.gnupg
      echo "pinentry-mode loopback" > ~/.gnupg/gpg.conf
      echo "${GPG_KEY}" | gpg --batch --import

builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    binary: '{{ .ProjectName }}_v{{ .Version }}'

archives:
  - format: zip
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - LICENSE

checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - artifacts: checksum
    cmd: gpg
    args:
      - --batch
      - --yes
      - --pinentry-mode
      - loopback
      - --passphrase
      - "${GPG_PASSPHRASE}"
      - --output
      - "${signature}"
      - --detach-sign
      - --armor
      - "${artifact}"

release:
  github:
    owner: ankraio
    name: terraform-provider-ankra
  draft: false
  prerelease: false

changelog:
  disable: true
