version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    binary: 'terraform-provider-ankra_v{{ .Version }}'

archives:
  - format: zip
    name_template: 'terraform-provider-ankra_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - LICENSE


checksum:
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: 'terraform-provider-{{ .ProjectName }}_{{ .Version }}_manifest.json'
  name_template: 'terraform-provider-{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  github:
    owner: ankraio
    name: terraform-provider-ankra
  draft: false
  prerelease: false
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: 'terraform-provider-{{ .ProjectName }}_{{ .Version }}_manifest.json'

changelog:
  disable: true
