version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    binary: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'

archives:
  - format: zip
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - LICENSE



checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS'
  algorithm: sha256


signs:
  - artifacts: checksum
    args:
      - --output
      - ${{ .Path }}.sig
      - --detach-sign
      - --armor
      - ${{ .Path }}
    cmd: gpg
    signature: ${{ .Path }}.sig
    env:
      - GPG_PASSPHRASE
      - GPG_FINGERPRINT



release:
  github:
    owner: ankraio
    name: terraform-provider-ankra
  draft: false
  prerelease: false

changelog:
  disable: true
